language: php

php:
  - 7.3

branches:
  only:
    - 2.x

services:
  - mysql

before_script:
  - cd docroot
  - composer install --dev
  - ./tests/setup_mysql.php

script:
  - phpunit
  - ./vendor/bin/behat
