version: '2.4'

services:
  db:
    image: mysql:5.7
    container_name: strava-db
    working_dir: /application
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 50
    volumes:
      - ./docroot:/application:cached
      - ./db-backups:/var/mysql/backups:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:3310:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 15s
      interval: 5m
      retries: 5

  webserver:
    image: nginx:1.19-alpine
    container_name: strava-webserver
    working_dir: /application
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 50
    volumes:
      - ./docroot:/application:cached
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:8084:80"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost" ]
      timeout: 5s
      interval: 5m
      retries: 5

  php-fpm:
    build: phpdocker/php-fpm
    container_name: strava-php-fpm
    working_dir: /application
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 200
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ./docroot:/application:cached
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    healthcheck:
      test: [ "CMD", "php", "--version" ]
      timeout: 5s
      interval: 5m
      retries: 5

  rabbitmq:
    image: bitnami/rabbitmq:3.8.5
    container_name: strava-rabbitmq
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 200
    volumes:
      - ./rabbitmq-persistence:/bitnami
    ports:
      - "127.0.0.1:15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "status" ]
      timeout: 15s
      interval: 5m
      retries: 5

  # php-cron:
  #   build: phpcron
  #   container_name: strava-php-cron
  #   working_dir: /application
  #   restart: always
  #   volumes:
  #     - ./docroot:/application:cached
  #     - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
  #     - ./cron/root:/etc/crontabs/root
