version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: strava-db
    working_dir: /application
    restart: always
    volumes:
      - ./docroot:/application:cached
      - ./db-backups:/var/mysql/backups:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3310:3306"

  webserver:
    image: nginx:alpine
    container_name: strava-webserver
    working_dir: /application
    restart: always
    volumes:
      - ./docroot:/application:cached
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8084:80"

  # I need to get crontab installed by default on this image. For now, after the
  # image is created, I just sh in and: apt update && apt install cron.
  php-fpm:
    build: phpdocker/php-fpm
    container_name: strava-php-fpm
    working_dir: /application
    restart: always
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ./docroot:/application:cached
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ./cron:/var/spool/cron/crontabs

  # php-cron:
  #   build: phpcron
  #   container_name: strava-php-cron
  #   working_dir: /application
  #   restart: always
  #   volumes:
  #     - ./docroot:/application:cached
  #     - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
  #     - ./cron/root:/etc/crontabs/root
