name: Composer CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Validate the composer file
      run: |
        cd docroot
        composer validate --no-check-all --ansi
